https://www.amazon.com/dp/B01M0JHG7Y (10 Pack (Green) Tactical BreakLights)
https://www.amazon.com/dp/B0744Z59WK (Combat Splint- (Olive Green) Recon Medical Combat Splint 36 inches)
https://www.amazon.com/dp/B07WW46HTF (AMK QuikClot Gauze 3 inch x 4 Foot)
https://www.amazon.com/dp/B075HJ1WNR (Tweezers Set 4-piece)
https://www.amazon.com/dp/B0753YDLLH (Pen Light, RISEMART Nurse Led Medical Penlight)
https://www.amazon.com/dp/B00YFG1U86 (Madison Supply - Medical Scissors, EMT and Trauma Shears, Premium Quality 7.5" - Fluoride-Coated with Non-Stick Blades 1-Pack)
